package.json, src/index.ts, src/types.d.ts, test/index.ts
1. This PR removes the test for initilizating an object without new
keyword.
2. extend is replaced by Object.assign.
=> chore: Deprecate initiliazation without new

src/index.ts, src/types.d.ts, test/index.ts
Fixes #20 
Adding support of labels via metadata in log entry (#20)
If the metadata contains a labels property, promote it to the entry metadata.  
See details in documentation:
https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry
=> Add support of labels via metadata in log entry (#20)

.circleci/config.yml
This change in the CircleCI config is needed so that compilation
can occur before publishing the module.
=> chore: add `npm install` before `npm publish`

.circleci/config.yml
To make lint work, we need to run `npm link` first, then `npm install`. Otherwise `npm install` won't be able to find the package being tested.
=> fix samples linting in circleci

src/index.ts, src/types/core.d.ts, test/index.ts
Fixes #42
specify labels metadata when initiate logger object
specify label like in console transporter
=> feature: allow specifying default labels in the constructor

src/types/core.d.ts, system-test/test-install.ts, test/index.ts
Also the type of the `labels` option has been updated to
`{[key: string]: string}`.
=> chore: add install tests for the label[s] options

src/index.ts, test/index.ts
Fixes the permanent merging of labels after logging a message with custom labels.
Fixes #88
=> fix: prevent permanent  merging of labels

system-test/logging-winston.ts
Both were writing to the default `winston_log` log in Stackdriver
and system tests would fail when unexpected logs would show up rather
than the expected logs.
Fixes #78 
Only the first commit needs to be reviewed.
=> test: fix race between sample and system tests

README.md
Since we are using a protobuf based transport, users need to format
according to the protobuf docs rather than the JSON/REST docs.
Fixes: https://github.com/googleapis/nodejs-logging-winston/issues/93
=> doc: fix link to HttpRequest message

package-lock.json, src/index.ts, src/types/core.d.ts
`types.Metadata|{}` was unnecessary as all properties in types.Metadata
are options. This leads to a fair amount of cleanup.
For JS this is a no-op, and I think it is a no-op for TypeScript users too, but keep me honest.
=> cleanup: get rid of unncessary type casts

package.json, system-test/errors-transport.ts
Move `common` to devDependencies. It is only used in
`errors-transport.ts` system tests.
Fixes: https://github.com/googleapis/nodejs-logging-winston/pull/151
=> fix(deps): update dependency @google-cloud/common to ^0.23.0

src/index.ts
Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)
=> fix: add missing docstring

package.json, src/winston3.ts, system-test/logging-winston.ts
handles bug reported in  #175
fixes propagation of error.stack so serviceContexts get sent to error reporting in winston 3
=> Doesnt set service context winston3

system-test/logging-winston.ts
1. The test timeout was not effectively applied.
2. All of the tests needed a longer timeout rather than just the error
reporting ones.
3. The error-reporting tests would race with a concurrent execution of
the tests in the CI because they were logging and polling against
the same service. Uniquify the service name.
Evidence of 2:
The default timeout was 10s.
=> fix: de-flake system tests

package.json, src/common.ts, src/middleware/express.ts, src/middleware/make-child-logger.ts, test/middleware/express.ts, test/middleware/make-child-logger.ts
Similar to `logging-bunyan`, this PR implements a request correlating middleware for express. This is WIP, but opening now to get early feedback.
=> feature: request logging middleware for express

src/common.ts, test/common.ts
Fixes: https://github.com/googleapis/nodejs-logging/issues/381
Please see: https://github.com/googleapis/google-cloud-node/issues/1987#issuecomment-279470870
Also see the matching PR that logging-bunyan received, that logging-winston did not:
https://github.com/googleapis/google-cloud-node/pull/2094
=> fix: remove circular references

system-test/errors-transport.ts, system-test/logging-winston.ts
The system tests for error reporting were still not safe to run
concurrently. The issue is that at the end we were deleting all events
(there is no API to delete events selectively, AFAICT). This meant that
concurrent executions of the system tests against the same project could
clobber anothers logged errors.
This is consistent with the observed timeouts looking for events to
show up.
Ref: https://github.com/googleapis/nodejs-logging-bunyan/pull/275
=> test: fix error reporting system test race

package.json
We use this at runtime.
Ref: https://github.com/googleapis/nodejs-logging-bunyan/issues/277
=> fix: add missing dep on google-auth-library

system-test/errors-transport.ts
The group can have related events from multiple services. Fix the filter
to ensure only the right events are returned.
Ref: https://github.com/googleapis/nodejs-logging-bunyan/pull/280
=> test: error-reporting system test improvement

src/common.ts, src/types/core.d.ts, test/common.ts
As a result of Winston 3 buffering, timestamps assigned in this transport (actually, assigned through [nodejs-logging](https://github.com/googleapis/nodejs-logging/blob/697711bfeaf5272c8bc272d2833e10b19253cd07/src/entry.ts#L110-L114)) aren't always accurate. We should prefer timestamps set by the user if it exists (the current behavior is to ignore it).
=> fix: assign timestamps from log metadata

src/common.ts, src/types/core.d.ts
In response to https://github.com/googleapis/nodejs-logging-winston/pull/294#issuecomment-481419796
=> fix: only copy timestamp metadata if it is a date

CHANGELOG.md, package.json, samples/package.json
---
@JustinBeckwith, @ofrobots meta conversation; I'm working on tooling around CHANGELOG generation (this is currently an annoying amount of manual cruft). 
I'd like to advocate that we potentially use the type `deps: upgraded @foo/module`, rather than `chore(deps)` or `fix(deps)`; if the dependency happened to fix something, we could add the note:
`deps: upgrade @foo/module to address bug bar`
if it's a breaking change:
```
deps: upgrade @foo/module
BREAKING CHANGE: @foo/module drops Node 6 support
```
:point_up: if we converge on a standard like this it will make tooling a bit easier; I'll write these thoughts up separately from here.
=> Release @google-cloud/logging-winston v0.11.1

.gitignore, package-lock.json, samples/package-lock.json, test/winston-2/package-lock.json
This is an experiment.  We started to ignore lock files when they caused conflicts and issues with `npm link ../` and samples tests.  This turns them back on so we can re-evaluate if they should be expanded more broadly.  FYI @ofrobots @bcoe
=> chore: add lock files back

README.md, samples/quickstart.js
Now that we do not support winston@2, remove winston@2 instructions
and winston@3 specific call-outs.
=> docs: update README/samples to target winston@3

package-lock.json, package.json, system-test/errors-transport.ts
Removes `teeny-request` and `@types/request` which were no longer required.
=> chore: clean up dev dependencies

package.json
`@compodoc/compodoc@1.1.9` fails to render markdown tables and JavaScript code blocks, I've opened a tracking issue here on compodoc:
https://github.com/compodoc/compodoc/issues/795
For the time being, pinning to `1.1.8` seems to put us in a better position.
fixes #335
=> fix(docs): pin to version of compodoc that renders JavaScript/tables

src/index.ts, system-test/test-install.ts
`transport-stream` uses a CommonJS style export. The way we were
importing was giving errors to using `esModuleInterop`. Use the special
syntax for this style of modules.
Fixes: #341
Fixes: #342
=> fix: properly import transport-stream

README.md, src/middleware/express.ts, system-test/test-middleware-express.ts
The request log message added by the middleware needs to have a
message property for winston to correctly format it.
Also default to the syslog log levels -- they map to stackdriver log
levels correctly.
Fixes #343
=> fix(middleware): need message in request log message

src/types/core.d.ts, test/index.ts
Most of the real work here is done in the `@google-cloud/logging` library.  We just need to make sure the option is passable to the underlying lib.
=> feat: add support for apiEndpoint override

.gitignore, package.json, src/middleware/make-child-logger.ts, test/middleware/make-child-logger.ts
Winston now provides a proper child logger API. Use that instead of
of our own approximation. This also changes behavior in that the child
loggers have /default/ metadata, but individual logs can override the
default. Our implementation was the other way around wherein the it was
not possible to override the default. The winston behavior seems
intuitively more correct. This is not semver major because the
middleware code is marked experimental.
=> fix(middleware): use winston provided child logger api

README.md, src/common.ts, src/middleware/express.ts, src/types/core.d.ts, system-test/test-middleware-express.ts, test/middleware/express.ts
BREAKING CHANGE: We now promote the `logEntry` metadata field in a
winston log info object to be the `logName` reported to Stackdriver. This means
that the logs will show up under the log name specified by the `logName`. In addition
there are several breaking changes to users of the express middleware:
* The middleware function has been replaced by makeMiddleware.
* makeMiddleware expects a winston logger to be passed in.
* Previously, we would append a `_applog` suffix to the user provided
application log name. We no longer do that. We use the user provided
log name for the application logs. The request logs now have a suffix.
Rationale:
Let the middleware users provide a winston logger that we annotate with a transport
rather than creating two winston loggers on user's behalf. We avoid …
=> feat(middleware)!: make API more ergonomic

.readme-partials.yaml, README.md, src/common.ts, src/middleware/express.ts, test/common.ts, test/middleware/express.ts
Sometimes the users may want to allocate the transport themeselves.
Fixes: https://github.com/googleapis/nodejs-logging-winston/issues/368
=> fix(middleware): allow users to provide middleware

package.json
make it explicit that we support only logging after the gcp-metadata fix
=> chore: update minimum support logging version

package.json, src/common.ts, src/types/core.d.ts, test/common.ts
This begins truncating logs to 250,000 bytes, so that we fall within the 256,000 byte limit (and don't throw an exception).
fixes #190.
=> feat!: logs now truncate to 250,000 bytes by default

.readme-partials.yaml
Link previously went nowhere, now it goes to product page. 
Main docs page is here: https://cloud.google.com/error-reporting/docs/
Fixes #422  🦕
Closes #423 (incorrectly implemented)
=> fix(docs): link to Stackdriver Error Reporting

.readme-partials.yaml, README.md
Fixes #453  🦕
Fixes broken/non-existing links for [HttpRequest](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#HttpRequest) reference and [@google-cloud/error-reporting](https://github.com/googleapis/nodejs-error-reporting) module's repository.
=> docs: fix some links in the documentation
