package.json, samples/package.json
Release notes drafted in the releases UI.
=> Bump version to 0.7.0

.circleci/config.yml, package.json, samples/quickstart.js, samples/setup_explicit.js, src/index.ts, src/types.d.ts, system-test/logging-winston.js
- 1. remove unused JSDoc.
- 2. Change some miscellaneous regarding type, comments, importing style, etc.
=> chore: Remove JS docs and miscellaneous

.circleci/config.yml
Run CI tasks as non-root to speedup things.
=> make CI run as non-root

.circleci/config.yml, package.json, samples/package.json
- This patch release updates dependencies of the package to fix a security issue caused by `log-driver` package. There are no other changes in this release.
=> releasing 0.8.1 with updated dependencies

package.json
Fixes: https://github.com/googleapis/nodejs-logging-winston/issues/57
=> chore(package): upgrade logging dep

package-lock.json, package.json, samples/package-lock.json, samples/package.json
The draft release notes are in the GitHub UI.
Fixes #67
=> chore: release v0.9.0

package.json
=> chore(package): update @types/node to version 10.0.9

.circleci/config.yml, package.json
=> chore: drop node 4 support

README.md, package.json, src/index.ts, system-test/errors-transport.ts, system-test/logging-winston.ts, test/index.ts
=> fix: logged errors are reported to error reporting

package.json, system-test/errors-transport.ts
Rebase and merge only after https://github.com/googleapis/nodejs-logging-winston/pull/152 lands.
=> feat: use small HTTP dependency

package.json
=> fix: presystem-test should run pretest

samples/package.json, samples/quickstart.js, system-test/logging-winston.ts
=> fix: fixing samples test and guarding for no entries in system test

package.json, src/common.ts, system-test/errors-transport.ts, system-test/logging-winston.ts, test/common.ts
Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)
=> fix: Upgrade to @google-cloud/logging 4.x

CHANGELOG.md, package.json, samples/package.json
=> Release @google-cloud/logging-winston v0.10.0

CHANGELOG.md, package.json, samples/package.json
=> Release @google-cloud/logging-winston v0.10.1

CHANGELOG.md, package.json, samples/package.json
=> Release @google-cloud/logging-winston v0.10.2

CHANGELOG.md, package.json, samples/package.json
=> Release @google-cloud/logging-winston v0.11.0

package-lock.json, package.json, src/index.ts, system-test/logging-winston.ts, test/index.ts
The unadorned level field may be modified by various formatters.
Symbol.for('level') holds the immutable level.
Fixes: https://github.com/googleapis/nodejs-logging-winston/issues/184
=> fix: use immutable winston level

.readme-partials.yaml
The actual README file and the template were out of sync.
=> doc: synchronize README template

README.md
Fix minor nit spelling error in README
=> chore: fix spelling error in README

src/default-metadata.ts, src/index.ts, test/stackdriver-trace-integration.ts
Fixes #287
~~Looking for API feedback before I write tests.~~
cc/ @googleapis/node-team
=> feat: add getDefaultMetadataForTracing

README.md
=> chore: fixing stackdriver logging link to suggested value

src/common.ts
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
Fixes an obvious typo (not actually a bug) 🦕
=> fix: correct a typo in a comment
